### ISSUE TITLE
Statusbar icon

### ISSUE THREAD

**Issue by ghost** [iexos/BipolAlarm#7]
It would be nice, when there is a statusbar icon, when the alarm is active.
So it is enough take one look one the phone to check if the alarm is active.

Thanks.

**Comment by iexos** [comment]
Android's native alarm indicator should be active when an alarm is set. This is what (at least on my phone) the standard alarm app does as well. I'd rather not add another redundant status bar icon.

**Comment by ghost** [comment]
On a Galaxy S3 and cyanogenmod there is only a icon in ringing 

Am 26. Januar 2016 07:21:59 MEZ, schrieb iexos notifications@github.com:

> Android's native alarm indicator should be active when an alarm is set.
> This is what (at least on my phone) the standard alarm app does as
> well. I'd rather not add another redundant status bar icon.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iexos/BipolAlarm/issues/7#issuecomment-174852061

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by iexos** [comment]
On the right hand side of the status bar is an alarm bell icon visible if an alarm is set in CM.

**Comment by ghost** [comment]
Thanks, now i see it :dancer:
